Repository hmcts/ccd-case-management-web, pull requests merged in 2018-12, with the labels that each got.

#447 tests for check your answers
  test/functional-tests/features/caseCreation.feature
  test/functional-tests/features/checkYourAnswers.feature
  test/functional-tests/pageObjects/basePage.js
  test/functional-tests/pageObjects/caseListPage.js
  test/functional-tests/pageObjects/createCaseStartPage.js
  test/functional-tests/pageObjects/createCaseWizardPage.js
  test/functional-tests/pageObjects/webdriver-components/dropdown.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
Labels: ns:ccd-case-management-web-pr-447

#449 Revert to V1 endpoints to fix Resume drafts in PROD.
  src/app/cases/creator/create-case-event-trigger.resolver.spec.ts
  src/app/cases/creator/create-case-event-trigger.resolver.ts
Labels: bug, ns:ccd-case-management-web-pr-449

#450 rdm-2009-update-toolkit-version
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-450

#448 RDM-3484 UI Toolkit: Use Start Event For Case API v2
  package.json
  src/app/cases/event-trigger/event-trigger.resolver.spec.ts
  src/app/cases/event-trigger/event-trigger.resolver.ts
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-448

#463 Update toolkit with v2.12.1
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-463

#457 bump toolkit version to 2.12
  src/style/app.scss
  yarn.lock
Labels: ns:ccd-case-management-web-pr-457

#462 RDM-3512 Implement internal Get Trigger for Draft endpoint in API v2
  package.json
  src/app/cases/creator/create-case-event-trigger.resolver.spec.ts
  src/app/cases/creator/create-case-event-trigger.resolver.ts
  src/app/cases/event-trigger/event-trigger.resolver.spec.ts
  src/app/cases/event-trigger/event-trigger.resolver.ts
  src/public/config.json
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-462

#467 Rdm 3512 Fix sonar scan issues with missing coverage.
  src/app/shared/search/search-result.component.spec.ts
Labels: enhancement, ns:ccd-case-management-web-pr-467

#466 Rdm 3502 UI Toolkit: Use Validate API v2
  package.json
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/case-creator-submit.component.ts
  src/app/cases/event-trigger/case-event-trigger.component.spec.ts
  src/app/cases/event-trigger/case-event-trigger.component.ts
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-466

#440 RDM-2994 Input filter Bug for long running requests
  src/app/core/search/search.service.ts
  src/app/shared/search/filters/search-filters.component.spec.ts
  src/app/shared/search/filters/search-filters.component.ts
  src/app/workbasket/filters/workbasket-filters.component.spec.ts
  src/app/workbasket/filters/workbasket-filters.component.ts
  src/app/workbasket/workbasket-input-filter.service.ts
Labels: ns:ccd-case-management-web-pr-440

#471 Work around AzureRM Terraform version issue
  infrastructure/main.tf
Labels: ns:ccd-case-management-web-pr-471
