Repository hmcts/ccd-case-management-web, pull requests merged in 2018-10, with the labels that each got.

#306 [PREVIEW] RDM-2569 Upgrade ui toolkit to 1.2.5
  package.json
  yarn.lock
Labels: enhancement

#299 [PREVIEW] Rdm 2510 As a user I want to see 'Drafts' regardless of what values are displayed in the first column on the case list + RDM-3006 Draft cases are not calculated in total number of cases
  src/app/shared/header/case-header.component.ts
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.component.ts
  src/app/shared/search/search-result.html
Labels: enhancement

#304 [PREVIEW] Ability to view case with case ID only
  src/app/app.routing.ts
  src/app/cases/case.resolver.spec.ts
  src/app/cases/case.resolver.ts
  src/app/core/cases/cases.service.spec.ts
  src/app/core/cases/cases.service.ts
  src/app/shared/case-history/case-history.resolver.spec.ts
  src/app/shared/case-history/case-history.resolver.ts
Labels: enhancement

#279 [PREVIEW] RDM-1864: Showing '-' if the cell value is empty
  src/app/shared/palette/date/read-date-field.component.spec.ts
  src/app/shared/palette/date/read-date-field.component.ts
  src/app/shared/palette/email/read-email-field.component.spec.ts
  src/app/shared/palette/email/read-email-field.component.ts
  src/app/shared/palette/fixed-list/read-fixed-list-field.component.spec.ts
  src/app/shared/palette/fixed-list/read-fixed-list-field.component.ts
  src/app/shared/palette/money-gbp/read-money-gbp-field.component.spec.ts
  src/app/shared/palette/money-gbp/read-money-gbp-field.component.ts
  src/app/shared/palette/multi-select-list/read-multi-select-list-field.component.spec.ts
  src/app/shared/palette/multi-select-list/read-multi-select-list-field.component.ts
  src/app/shared/palette/multi-select-list/read-multi-select-list-field.html
  src/app/shared/palette/number/read-number-field.component.spec.ts
  src/app/shared/palette/number/read-number-field.component.ts
  src/app/shared/palette/order-summary/read-order-summary-field.component.spec.ts
  src/app/shared/palette/order-summary/write-order-summary-field.component.spec.ts
  src/app/shared/palette/phone-uk/read-phone-uk-field.component.spec.ts
  src/app/shared/palette/phone-uk/read-phone-uk-field.component.ts
  src/app/shared/palette/text-area/read-text-area-field.component.spec.ts
  src/app/shared/palette/text-area/read-text-area-field.component.ts
  src/app/shared/palette/text/read-text-field.component.spec.ts
  src/app/shared/palette/text/read-text-field.component.ts
  src/app/shared/palette/yes-no/read-yes-no-field.component.ts
  src/style/app.scss
Labels: enhancement

#314 [PREVIEW] RDM-3052: Update Pay web components
  package.json
  yarn.lock
Labels: dependencies

#312 [PREVIEW] RDM-2881: Fix empty heading in Collection fields
  src/app/shared/palette/collection/collection-field.scss
  src/app/shared/palette/collection/write-collection-field.html
  src/style/app.scss
Labels: enhancement

#309 [PREVIEW] RDM-3017: GDPR updates for Financial Remedy
  src/app/footer-nav/contact-us.component.html
  src/app/footer-nav/cookies.component.html
  src/app/footer-nav/privacy.component.html
  src/app/footer-nav/tc.component.html
Labels: enhancement

#289 [PREVIEW] RDM-2886: Make column sort link accessible
  src/app/shared/search/search-result.html
  src/app/shared/search/search-result.scss
Labels: enhancement

#288 [PREVIEW] RDM-2888: Add description to case link in case table
  src/app/shared/search/search-result.html
Labels: enhancement

#316 [PREVIEW] RDM-2901: Significant item link frontend change
  src/app/cases/viewer/case-viewer.component.spec.ts
  src/app/core/cases/case-view-event.model.ts
  src/app/shared/event-log/event-log-details.component.spec.ts
  src/app/shared/event-log/event-log-table.component.spec.ts
  src/app/shared/event-log/event-log-table.component.ts
  src/app/shared/event-log/event-log-table.html
  src/app/shared/event-log/event-log-table.scss
  src/app/shared/event-log/event-log.component.spec.ts
  src/public/img/doc-link.png
  src/style/app.scss
Labels: enhancement

#300 [PREVIEW] RDM-2891: Add accessible description to Document field
  src/app/shared/palette/document/write-document-field.html
Labels: enhancement

#295 Rdm 2302 As a user I want to 'cancel and return' during a create event
  src/app/cases/creator/case-creator-submit.component.html
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/case-creator-submit.component.ts
  src/app/cases/creator/create-case-event-trigger.resolver.spec.ts
  src/app/cases/creator/create-case-event-trigger.resolver.ts
  src/app/cases/event-trigger/case-event-trigger.html
  src/app/cases/viewer/case-viewer.component.spec.ts
  src/app/cases/viewer/case-viewer.component.ts
  src/app/core/draft/draft.service.ts
  src/app/core/form/form-value.service.ts
  src/app/shared/case-editor/case-edit-form.component.ts
  src/app/shared/case-editor/case-edit-page.component.spec.ts
  src/app/shared/case-editor/case-edit-page.component.ts
  src/app/shared/case-editor/case-edit-page.html
  src/app/shared/case-editor/case-edit-submit.html
  src/app/shared/case-editor/case-edit.component.spec.ts
  src/app/shared/case-editor/case-edit.component.ts
  src/app/shared/domain/draft.ts
  src/app/shared/event-trigger/event-trigger.component.ts
  src/app/shared/save-or-discard-dialog/save-or-discard-dialog.component.html
  src/app/shared/save-or-discard-dialog/save-or-discard-dialog.component.spec.ts
  src/app/shared/save-or-discard-dialog/save-or-discard-dialog.component.ts
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.component.ts
  src/app/shared/shared.module.ts
  src/app/shared/utils/case-reference.pipe.ts
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.component.ts
Labels: enhancement

#328 [PREVIEW] RDM-2886-revert: This is to revert RDM-2886 to resolve sorting issue.
  src/app/shared/search/search-result.html
Labels: bug

#321 [PREVIEW] RDM-3118: Added the table in Cookies GDPR
  src/app/footer-nav/cookies.component.html
Labels: enhancement

#351 RDM 3144 - Use new endpoint for jurisdictions with access type
  package.json
  src/app/cases/creator/case-creator.component.html
  src/app/cases/creator/filters/create-case-filters.component.spec.ts
  src/app/cases/creator/filters/create-case-filters.component.ts
  src/app/core/definitions/definitions.service.spec.ts
  src/app/core/definitions/definitions.service.ts
  src/app/shared/search/filters/search-filters.component.ts
  src/app/workbasket/filters/workbasket-filters.component.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-351

#353 Travis cleanup
  .travis.yml
Labels: ns:ccd-case-management-web-pr-353

#346 [PREVIEW] RDM-3135: Updated case list and search results after apply
  src/app/search/search.component.html
  src/app/shared/search/filters/search-filters.html
  src/app/workbasket/filters/workbasket-filters.html
  src/app/workbasket/workbasket.component.html
Labels: enhancement, ns:ccd-case-management-web-pr-346

#354 [PREVIEW] Rdm 3178 + RDM 3179 + bug fix to cancel on CYA page of create case event with S&R: Release new version
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/case-creator-submit.component.ts
Labels: ns:ccd-case-management-web-pr-354

#376 Run Saucelabs nightly
  Jenkinsfile_nightly
  test/config/crossbrowser.conf.js
Labels: ns:ccd-case-management-web-pr-376

#364 [PREVIEW] RDM-3068: Update tooltip style of ccd activity field
  src/app/core/activity/ccd-activity/ccd-activity-icon/ccd-activity-icon.component.css
Labels: bug, ns:ccd-case-management-web-pr-364

#365 [PREVIEW] Rdm 3138 Add more FE Tests
  Jenkinsfile_nightly
  package.json
  test/functional-tests/config/local.conf.js
  test/functional-tests/features/fieldTypes.feature
  test/functional-tests/features/login.feature
  test/functional-tests/pageObjects/basePage.js
  test/functional-tests/pageObjects/caseListPage.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdCollectionField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdDateField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdFixedList.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdStringField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdTextAreaField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdYesNoField.js
  test/functional-tests/pageObjects/ccd-components/footerComponent.js
  test/functional-tests/pageObjects/ccd-components/globalNavBar.js
  test/functional-tests/pageObjects/ccd-components/workbasketComponent.js
  test/functional-tests/pageObjects/createCaseStartPage.js
  test/functional-tests/pageObjects/createCaseWizardPage.js
  test/functional-tests/pageObjects/loginPage.js
  test/functional-tests/pageObjects/webdriver-components/dropdown.js
  test/functional-tests/pageObjects/webdriver-components/textField.js
  test/functional-tests/stepDefinitions/baseSteps.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
  test/functional-tests/stepDefinitions/loginSteps.js
  test/functional-tests/utils/ccdDataGenerationUtils.js
  test/functional-tests/utils/errors/custom-error.js
  test/functional-tests/utils/fieldUtils.js
Labels: ns:ccd-case-management-web-pr-365
