Repository hmcts/ccd-case-management-web, pull requests merged in 2018-11, with the labels that each got.

#383 Make crossBrowser test run optional
  Jenkinsfile_nightly
Labels: ns:ccd-case-management-web-pr-383

#371 RDM-3141: Corrected the header elements
  src/app/shared/event-log/event-log.html
  src/app/shared/header/case-header.component.spec.ts
  src/app/shared/header/case-header.html
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-371

#372 [PREVIEW] RDM-3140: Accesibility inform user of number of results
  src/app/shared/search/search-result.html
Labels: enhancement, ns:ccd-case-management-web-pr-372

#394 Rdm 3230 directory structure
  src/app/cases/cases.module.ts
  src/app/shared/shared.module.ts
Labels: enhancement

#384 Bump minimum Node.js to v8.11.1
  package.json
Labels: ns:ccd-case-management-web-pr-384

#396 [PREVIEW] RDM-3203: Fix payment listing in history
  src/app/shared/case-history/case-history.component.html
  src/app/shared/case-history/case-history.component.spec.ts
Labels: bug, ns:ccd-case-management-web-pr-396

#341 [PREVIEW] Rdm 654 - Sticky Search functionality using localStorage
  package.json
  src/app/core/search/field.model.ts
  src/app/core/search/search-input.test.fixture.ts
  src/app/core/utils/window.service.ts
  src/app/search/search.component.html
  src/app/search/search.component.spec.ts
  src/app/search/search.component.ts
  src/app/shared/search/filters/search-filters.component.spec.ts
  src/app/shared/search/filters/search-filters.component.ts
  src/app/shared/search/search-result.component.ts
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.ts
  src/app/workbasket/filters/workbasket-filters.component.spec.ts
  src/app/workbasket/filters/workbasket-filters.component.ts
  src/app/workbasket/workbasket-input-filter.service.spec.ts
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.component.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-341

#350 [PREVIEW] Rdm 2909 - Reset search and workbasket filter criteria
  src/app/core/utils/window.service.ts
  src/app/search/search.component.html
  src/app/search/search.component.ts
  src/app/shared/search/filters/search-filters.component.spec.ts
  src/app/shared/search/filters/search-filters.component.ts
  src/app/shared/search/filters/search-filters.html
  src/app/shared/search/search-result.component.ts
  src/app/workbasket/filters/workbasket-filters.component.spec.ts
  src/app/workbasket/filters/workbasket-filters.component.ts
  src/app/workbasket/filters/workbasket-filters.html
Labels: ns:ccd-case-management-web-pr-350

#406 [PREVIEW] Disabling Smoke
  package.json
Labels: ns:ccd-case-management-web-pr-406

#385 [PREVIEW] RDM-3230 Make sure DialogsModule is imported properly.
  .travis.yml
  package.json
  src/app/cases/case.resolver.spec.ts
  src/app/cases/cases.module.ts
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/filters/create-case-filters.component.spec.ts
  src/app/cases/viewer/case-viewer.component.spec.ts
  src/app/core/activity/activity.polling.service.ts
  src/app/core/activity/ccd-activity/ccd-activity.component.spec.ts
  src/app/core/auth/oauth2.service.spec.ts
  src/app/core/profile/profile.resolver.spec.ts
  src/app/shared/case-history/case-history.resolver.spec.ts
  src/app/shared/event-log/event-log-details.component.spec.ts
  src/app/shared/event-log/event-log-table.component.spec.ts
  src/app/shared/event-log/event-log.component.spec.ts
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.spec.ts
  src/app/shared/shared.module.ts
  src/app/workbasket/workbasket-input-filter.service.spec.ts
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.module.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-385

#407 Temporarily disable vault reading
  Jenkinsfile_nightly
Labels: ns:ccd-case-management-web-pr-407

#408 RDM-3232: Complex type width defects fixed
  src/app/cases/viewer/case-viewer.component.html
  src/app/cases/viewer/case-viewer.component.spec.ts
  src/app/cases/viewer/case-viewer.scss
Labels: enhancement, ns:ccd-case-management-web-pr-408

#411 Enable Smoke Tests
  package.json
Labels: ns:ccd-case-management-web-pr-411

#415 Sync yarn.lock with package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-415

#397 Functional test updates
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  README.md
  package.json
  test/functional-tests/config/local.conf.js
  test/functional-tests/features/fieldTypes.feature
  test/functional-tests/features/login.feature
  test/functional-tests/pageObjects/basePage.js
  test/functional-tests/pageObjects/caseListPage.js
  test/functional-tests/pageObjects/ccd-components/caseListComponent.js
  test/functional-tests/pageObjects/loginPage.js
  test/functional-tests/pageObjects/webdriver-components/button.js
  test/functional-tests/stepDefinitions/baseSteps.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
  test/functional-tests/stepDefinitions/definitionFileSteps.js
  test/functional-tests/stepDefinitions/loginSteps.js
  test/functional-tests/utils/world.js
Labels: ns:ccd-case-management-web-pr-397

#375 [PREVIEW] RDM-3000 MidEvent callback
  package.json
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/case-creator-submit.component.ts
  src/app/cases/creator/filters/create-case-filters.component.spec.ts
  src/app/cases/creator/filters/create-case-filters.component.ts
  src/app/cases/creator/filters/create-case-filters.html
  src/app/cases/event-trigger/case-event-trigger.component.spec.ts
  src/app/cases/event-trigger/case-event-trigger.component.ts
  src/app/cases/viewer/case-viewer.component.html
  src/app/cases/viewer/case-viewer.component.spec.ts
  src/app/cases/viewer/case-viewer.component.ts
  stubs/api/aggregated.api.json
  stubs/api/aggregated.routes.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-375

#423 change smoke test run format to old original smoke tests
  package.json
Labels: ns:ccd-case-management-web-pr-423

#424 Rdm 3230 Remove duplicated profile service and import from ui toolkit.
  src/app/core/core.module.ts
  src/app/core/profile/profile.resolver.ts
  src/app/core/profile/profile.service.spec.ts
  src/app/core/profile/profile.service.ts
  src/app/shared/event-log/event-log-details.component.spec.ts
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-424

#431 [Preview] update-to-use-version-2.6.0-of-ccd-case-ui-toolkit
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-431

#370 [PREVIEW] RDM-2883: Adding the caption to the tables
  src/app/search/search.component.html
  src/app/shared/event-log/event-log-details.html
  src/app/shared/event-log/event-log-details.scss
  src/app/shared/event-log/event-log-table.html
  src/app/shared/event-log/event-log.html
  src/app/shared/event-log/event-log.scss
  src/app/shared/search/filters/search-filters.html
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.html
  src/app/shared/search/search-result.scss
  src/app/workbasket/filters/workbasket-filters.html
  src/app/workbasket/filters/workbasket-filters.scss
  src/app/workbasket/workbasket.component.html
  src/app/workbasket/workbasket.scss
  src/style/app.scss
  test/end-to-end/specs/login/login.ccd.spec.js
  test/page-objects/caseListFilters.po.js
Labels: bug, ns:ccd-case-management-web-pr-370

#438 [PREVIEW] RDM-3438: Create new case button fix
  src/app/workbasket/workbasket.scss
Labels: bug, ns:ccd-case-management-web-pr-438

#416 added scenarios for case progression
  docker-compose.yml
  package.json
  test/functional-tests/features/caseProgression.feature
  test/functional-tests/features/fieldTypes.feature
  test/functional-tests/features/login.feature
  test/functional-tests/pageObjects/caseDetailsPage.js
  test/functional-tests/pageObjects/createCaseWizardPage.js
  test/functional-tests/pageObjects/webdriver-components/button.js
  test/functional-tests/pageObjects/webdriver-components/dropdown.js
  test/functional-tests/stepDefinitions/caseDetailsSteps.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
  test/functional-tests/stepDefinitions/definitionFileSteps.js
  test/functional-tests/stepDefinitions/loginSteps.js
  test/functional-tests/utils/TestData.js
Labels: ns:ccd-case-management-web-pr-416

#439 [PREVIEW] RDM-3285 Up version of ccpay-web-component to add support for viewing…
  package.json
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-439

#441 RDM-3427 UI Toolkit: Use Start Event API v2
  package.json
  src/app/cases/creator/create-case-event-trigger.resolver.spec.ts
  src/app/cases/creator/create-case-event-trigger.resolver.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-441

#446 RDM-3463: Update to Version 2.8.1 of ccd-case-ui-toolkit library
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-446
