Repository hmcts/ccd-case-management-web, pull requests merged in 2019-11, with the labels that each got.

#820 reenable functional tests
  package.json
  test/features/media-viewer.feature
Labels: ns:ccd-case-management-web-pr-820

#790 RDM-5649 Functional tests for RDM-5594. Log out feature.
  package.json
  test/features/caseUpdate.feature
  test/features/login.feature
  test/pageObjects/caseDetailsPage.js
  test/pageObjects/ccd-components/globalNavBar.js
  test/pageObjects/loginPage.js
  test/pageObjects/wizardPages/ComplexCollectionComplex/createQandAPage.js
  test/resources/definitionsFiles/fe-automation-definition-v26_RDM-5649_COMPLEX_CRUD_CUSTOM.xlsx
  test/resources/definitionsFiles/fe-automation-definition-v29_complexcrud.xlsx
  test/stepDefinitions/caseDetailsSteps.js
  test/stepDefinitions/caseListSteps.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
  test/stepDefinitions/loginSteps.js
  yarn.lock
Labels: ns:ccd-case-management-web-pr-790

#818 RDM-5296 Bump up toolkit version
  yarn.lock
Labels: ns:ccd-case-management-web-pr-818

#812 RDM-6084 Fix for a caseLink to open the case in new tab.
  package.json
  src/app/search/search.component.html
  src/app/search/search.component.ts
  src/app/workbasket/workbasket.component.html
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.component.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-812

#816 RDM-6350 NavigationListenerService to announce any navigation errors via ErrorNotifierService.
  package.json
  src/app/core/core.module.ts
  src/app/core/utils/navigation-listener.service.spec.ts
  src/app/core/utils/navigation-listener.service.ts
  yarn.lock
Labels: bug, ns:ccd-case-management-web-pr-816

#825 Bumping to latest chart
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/requirements.yaml
Labels: ns:ccd-case-management-web-pr-825

#791 Rdm 4335 Implement and consume external POST Create Case endpoint in API v2
  package.json
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/case-creator-submit.component.ts
  test/features/login.feature
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-791

#832 RDM 4837
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-832

#823 RDM-5533 Disable X-Powered-By header
  angular.json
  server.ts
  web.config
Labels: ns:ccd-case-management-web-pr-823
