Repository hmcts/ccd-case-management-web, pull requests merged in 2019-09, with the labels that each got.

#761 RDM-5196
  src/app/search/search.component.html
  src/app/search/search.component.spec.ts
  src/app/search/search.component.ts
  src/app/workbasket/workbasket.component.html
  src/app/workbasket/workbasket.component.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-761

#762 Rdm 4617
  package.json
  src/app/cases/cases.module.ts
  src/app/core/core.component.spec.ts
  src/app/core/core.component.ts
  src/app/core/core.module.ts
  src/app/core/utils/navigation-listener.service.spec.ts
  src/app/core/utils/navigation-listener.service.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-762

#756 RDM-4648- Functional tests for dynamicists
  package.json
  test/features/fieldTypes.feature
  test/pageObjects/wizardPages/dataFieldTypesPage.js
  test/resources/definitionsFiles/fe-automation-definition-v21_RDM-4648_dynamiclists.xlsx
  test/resources/definitionsFiles/fe-automation-definition-v24_RDM-4648_dynamicilst_tests.xlsx
  test/resources/definitionsFiles/fe-automation-definition-v26_RDM-4648_dynamicilst_tests.xlsx
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
Labels: ns:ccd-case-management-web-pr-756

#794 Rdm 5509/pay 1732/v2.0.50
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-794

#799 Rdm 5930 new - Rdm 5930 - Upgrade patch to patch=2.7.5-1+deb9u2
  .project
  Dockerfile
Labels: ns:ccd-case-management-web-pr-799
