Repository hmcts/ccd-case-management-web, pull requests merged in 2019-01, with the labels that each got.

#468 [PREVIEW] RDM-3501 Bump up toolkit version.
  package.json
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-468

#453 Conditional functional tests
  Jenkinsfile_CNP
  test/functional-tests/features/conditionalLogic.feature
  test/functional-tests/features/fieldTypes.feature
  test/functional-tests/pageObjects/basePage.js
  test/functional-tests/pageObjects/caseDetailsPage.js
  test/functional-tests/pageObjects/createCaseWizardPage.js
  test/functional-tests/pageObjects/webdriver-components/button.js
  test/functional-tests/stepDefinitions/baseSteps.js
  test/functional-tests/stepDefinitions/caseDetailsSteps.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
  test/functional-tests/stepDefinitions/cyaSteps.js
  test/functional-tests/stepDefinitions/definitionFileSteps.js
  test/functional-tests/stepDefinitions/loginSteps.js
  test/functional-tests/stepDefinitions/testSetup.js
  test/functional-tests/stepDefinitions/validationSteps.js
Labels: ns:ccd-case-management-web-pr-453

#475 [PREVIEW] Use new secret loading structure
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  infrastructure/outputs.tf
Labels: ns:ccd-case-management-web-pr-475

#474 RDM-3574 Use new V2 draft endpoints.
  package.json
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/app/cases/case.resolver.spec.ts
  src/app/cases/case.resolver.ts
  src/app/cases/creator/case-creator-submit.component.spec.ts
  src/app/cases/creator/case-creator-submit.component.ts
  src/app/cases/viewer/case-viewer.component.ts
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-474

#481 update toolkit version and yarn.lock
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-481

#483 Update toolkit version to v2.20.1
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-483

#484 Revert toolkit version to 2.19.1
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-484

#476 Rdm 3563 Use Get WorkBasketInputDetails API v2
  src/app/app.config.spec.ts
  src/app/workbasket/workbasket-input-filter.service.spec.ts
  src/app/workbasket/workbasket-input-filter.service.ts
  src/app/workbasket/workbasket-input.model.ts
  stubs/api/aggregated.api.json
  stubs/functional/aggregated.api.json
Labels: enhancement, ns:ccd-case-management-web-pr-476

#477 Rdm 3565 UI Toolkit: Use Get CaseHistoryForEvent API v2
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/app/core/cases/case-history.service.spec.ts
  src/app/core/cases/case-history.service.ts
  src/app/shared/case-history/case-history.resolver.spec.ts
  src/app/shared/case-history/case-history.resolver.ts
  src/app/workbasket/workbasket-input-filter.service.spec.ts
Labels: enhancement, ns:ccd-case-management-web-pr-477

#487 Revert "Rdm 3565 UI Toolkit: Use Get CaseHistoryForEvent API v2"
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/app/core/cases/case-history.service.spec.ts
  src/app/core/cases/case-history.service.ts
  src/app/shared/case-history/case-history.resolver.spec.ts
  src/app/shared/case-history/case-history.resolver.ts
  src/app/workbasket/workbasket-input-filter.service.spec.ts
Labels: ns:ccd-case-management-web-pr-487

#486 [PREVIEW] RDM-3655: Contents of a long fields are truncated when displayed
  src/style/app.scss
Labels: bug, ns:ccd-case-management-web-pr-486

#382 [PREVIEW] RDM-2886: Making column sort link accessible
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.component.ts
  src/app/shared/search/search-result.html
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.ts
Labels: enhancement, ns:ccd-case-management-web-pr-382

#489 RDM-3570: Set SProd hostname
  infrastructure/sprod.tfvars
Labels: ns:ccd-case-management-web-pr-489

#488 Revert "Revert "Rdm 3565 UI Toolkit: Use Get CaseHistoryForEvent API v2""
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/app/core/cases/case-history.service.spec.ts
  src/app/core/cases/case-history.service.ts
  src/app/shared/case-history/case-history.resolver.spec.ts
  src/app/shared/case-history/case-history.resolver.ts
  src/app/workbasket/workbasket-input-filter.service.spec.ts
Labels: ns:ccd-case-management-web-pr-488

#347 Use shared app insight
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:ccd-case-management-web-pr-347

#490 [PREVIEW] RDM-2752: Provide Any option in the State Field for CaseList
  src/app/shared/search/search-result.scss
  src/app/workbasket/filters/workbasket-filters.component.spec.ts
  src/app/workbasket/filters/workbasket-filters.component.ts
  src/app/workbasket/filters/workbasket-filters.html
Labels: enhancement, ns:ccd-case-management-web-pr-490

#494 Use `-ccd.demo` DNS
  infrastructure/demo.tfvars
Labels: ns:ccd-case-management-web-pr-494

#496 Update toolkit version to v2.21.2
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-496

#492 [PREVIEW] RDM-3631: Adding Family Public Law content
  src/app/footer-nav/contact-us.component.html
  src/app/footer-nav/cookies.component.html
  src/app/footer-nav/privacy.component.html
  src/app/footer-nav/tc.component.html
  src/app/shared/accordion/accordion.component.html
Labels: enhancement, ns:ccd-case-management-web-pr-492

#422 Update yarn minimum version
  .travis.yml
  Dockerfile
  package.json
Labels: ns:ccd-case-management-web-pr-422

#504 RDM-3860: Update gateway DNS in AAT
  infrastructure/aat.tfvars
Labels: ns:ccd-case-management-web-pr-504

#503 Migrate to Helm charts
  Jenkinsfile_CNP
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/requirements.yaml
  charts/ccd-case-management-web/values.aat.template.yaml
  charts/ccd-case-management-web/values.template.yaml
  kubernetes/config.aat.yaml
  kubernetes/config.saat.yaml
  kubernetes/deployment.template.yaml
Labels: ns:ccd-case-management-web-pr-503

#506 Remove Helm alias
  charts/ccd-case-management-web/requirements.yaml
  charts/ccd-case-management-web/values.aat.template.yaml
  charts/ccd-case-management-web/values.template.yaml
Labels: ns:ccd-case-management-web-pr-506
