Repository hmcts/ccd-case-management-web, pull requests merged in 2019-04, with the labels that each got.

#632 SPROD
  package.json
Labels: ns:ccd-case-management-web-pr-632

#638 Switch Demo
  infrastructure/demo.tfvars
Labels: ns:ccd-case-management-web-pr-638

#634 RDM-2348-2: Grey bar styling
  package.json
  src/style/app.scss
  test/features/caseList.feature
  test/features/conditionalLogic.feature
  test/features/fieldTypes.feature
  test/pageObjects/createCaseWizardPage.js
  test/stepDefinitions/create-caseSteps.js
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-634

#648 updated toolkit version
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-648

#651 Update toolkit version
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-651

#627 RDM-3859 Add case view feature tests. Introduce a way to populate fie…
  .gitignore
  test/README.md
  test/features/caseView.feature
  test/pageObjects/caseDetailsPage.js
  test/pageObjects/ccd-components/fields/ccdFixedList.js
  test/pageObjects/ccd-components/fields/ccdStringField.js
  test/pageObjects/ccd-components/fields/ccdYesNoField.js
  test/pageObjects/createCaseWizardPage.js
  test/pageObjects/webdriver-components/dropdown.js
  test/stepDefinitions/baseSteps.js
  test/stepDefinitions/caseDetailsSteps.js
  test/stepDefinitions/definitionFileSteps.js
  test/utils/TestData.js
  test/utils/fieldUtils.js
Labels: enhancement, ns:ccd-case-management-web-pr-627

#653 RDM-4591: Toolkit version updated
  package.json
  yarn.lock
Labels: bug, ns:ccd-case-management-web-pr-653

#560 RDM-3940 ccdLabelSubstitutor will take caseFields instead of eventFields
  package.json
  src/app/shared/search/search-result.html
  test/features/complexTypes.feature
  test/pageObjects/ccd-components/fields/ccdDateField.js
  test/pageObjects/ccd-components/fields/ccdFixedList.js
  test/pageObjects/ccd-components/fields/ccdStringField.js
  test/pageObjects/ccd-components/fields/ccdYesNoField.js
  test/pageObjects/createCaseWizardPage.js
  test/pageObjects/webdriver-components/dropdown.js
  test/pageObjects/webdriver-components/radioField.js
  test/pageObjects/webdriver-components/textField.js
  test/resources/definitionsFiles/fe-automation-definition-v04.xlsx
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
  test/stepDefinitions/searchSteps.js
  test/utils/fieldUtils.js
  yarn.lock
Labels: ns:ccd-case-management-web-pr-560

#637 RDM-4184 Update func tests and spreadsheet to reflect removing of the…
  test/features/caseProgression.feature
  test/features/conditionalLogic.feature
  test/resources/definitionsFiles/fe-automation-definition-v03.xlsx
  test/stepDefinitions/caseDetailsSteps.js
Labels: enhancement, ns:ccd-case-management-web-pr-637

#608 Rdm 4130 as is
  package.json
  src/app/core/core.module.ts
  src/app/core/pagination/pagination.service.ts
  src/app/search/search.component.ts
  src/app/search/search.module.ts
  src/app/shared/search/pagination-metadata.model.ts
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.component.ts
  src/app/shared/search/search-result.html
  src/app/shared/search/search-result.scss
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.spec.ts
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.ts
  src/app/shared/search/sorting/search-result-view-item-comparator.ts
  src/app/shared/search/sorting/sort-order.ts
  src/app/shared/search/sorting/sort-parameters.ts
  src/app/shared/search/sorting/sort-search-result.pipe.ts
  src/app/shared/shared.module.ts
  src/app/workbasket/workbasket.component.ts
  src/app/workbasket/workbasket.module.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-608
