Repository hmcts/ccd-case-management-web, pull requests merged in 2019-03, with the labels that each got.

#556 Rdm 3916 case filter new contract
  package.json
  src/app/cases/creator/case-creator.component.html
  src/app/cases/creator/case-creator.component.spec.ts
  src/app/cases/creator/case-creator.component.ts
  test/functional-tests/features/caseFilters.feature
  test/functional-tests/stepDefinitions/create-caseSteps.js
  yarn.lock
Labels: ns:ccd-case-management-web-pr-556

#566 Update SAAT to Tidam
  infrastructure/saat.tfvars
Labels: ns:ccd-case-management-web-pr-566

#567 run tests in parallel
  README.md
  bin/runFunctionalTests.sh
  bin/runSmokeTests.sh
  test/config/conf.js
  test/features/conditionalLogic.feature
Labels: ns:ccd-case-management-web-pr-567

#573 Consume Search V2 API endpoint
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-573

#557 RDM-3972: Hyphen missing in case reference
  package.json
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.component.ts
  yarn.lock
Labels: bug, ns:ccd-case-management-web-pr-557

#541 RDM-3936: Court Admin footer
  src/app/core/core.component.html
  src/app/core/core.component.spec.ts
  src/app/core/core.component.ts
Labels: enhancement, ns:ccd-case-management-web-pr-541

#578 Toolkit version update to 2.32.0
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-578

#574 increased test login timeout
  test/config/conf.js
  test/pageObjects/basePage.js
  test/pageObjects/caseListPage.js
  test/pageObjects/webdriver-components/button.js
  test/stepDefinitions/loginSteps.js
Labels: ns:ccd-case-management-web-pr-574

#583 Consume toolkit v2.33 - flexible case history tab
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-583

#589 add tests for event timeline
  test/features/caseProgression.feature
  test/pageObjects/caseDetailsPage.js
  test/pageObjects/webdriver-components/dropdown.js
  test/resources/definitionsFiles/fe-automation-definition-v03.xlsx
  test/stepDefinitions/caseDetailsSteps.js
Labels: ns:ccd-case-management-web-pr-589

#587 added test for case ref
  test/features/caseList.feature
  test/features/caseProgression.feature
  test/pageObjects/caseDetailsPage.js
  test/pageObjects/ccd-components/caseListComponent.js
  test/pageObjects/ccd-components/globalNavBar.js
  test/pageObjects/webdriver-components/dropdown.js
  test/resources/definitionsFiles/fe-automation-definition-v02.xlsx
  test/resources/definitionsFiles/fe-automation-definition-v03.xlsx
  test/stepDefinitions/baseSteps.js
  test/stepDefinitions/caseDetailsSteps.js
  test/stepDefinitions/caseListSteps.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
Labels: ns:ccd-case-management-web-pr-587

#584 Upgrading to latest node chart and removing releasenameoverride
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/requirements.yaml
  charts/ccd-case-management-web/values.template.yaml
Labels: ns:ccd-case-management-web-pr-584

#550 RDM-3699: Fonts improvement through out CCD
  package.json
  src/app/cases/creator/case-creator.component.html
  src/app/error/error.html
  src/app/footer-nav/contact-us.component.html
  src/app/footer-nav/cookies.component.html
  src/app/footer-nav/footer-nav.component.scss
  src/app/footer-nav/privacy.component.html
  src/app/footer-nav/tc.component.html
  src/app/oauth2/oauth2-redirect.html
  src/app/search/search.component.html
  src/app/shared/accordion/accordion.component.html
  src/app/shared/accordion/accordion.component.scss
  src/app/shared/header/event-trigger-header.html
  src/app/shared/search/search-result.html
  src/app/shared/search/search-result.scss
  src/app/workbasket/filters/workbasket-filters.html
  src/app/workbasket/filters/workbasket-filters.scss
  src/app/workbasket/workbasket.component.html
  src/app/workbasket/workbasket.scss
  src/style/app.scss
  test/pageObjects/caseListPage.js
  test/pageObjects/ccd-components/fields/ccdCollectionField.js
  test/pageObjects/ccd-components/fields/ccdComplexTypeField.js
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-550

#596 Switch AAT to SIDAM
  infrastructure/aat.tfvars
  infrastructure/preview.tfvars
Labels: ns:ccd-case-management-web-pr-596

#600 Switch AAT to SIDAM
  charts/ccd-case-management-web/values.aat.template.yaml
Labels: ns:ccd-case-management-web-pr-600
