Repository hmcts/ccd-case-management-web, pull requests merged in 2019-02, with the labels that each got.

#510 Rdm 3849
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-510

#520 Demo toolkit update
  package.json
  src/app/cases/creator/filters/create-case-filters.component.spec.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-520

#461 added script to setup toolkit + management-web locally
  bin/local-toolkit-manweb-steup.sh
Labels: ns:ccd-case-management-web-pr-461

#525 Update toolkit version to v2.23.5
  package.json
  src/public/img/doc-link.png
  yarn.lock
Labels: ns:ccd-case-management-web-pr-525

#523 Use ACR cache optimisation in CI
  .dockerignore
  Dockerfile
  acb.tpl.yaml
Labels: ns:ccd-case-management-web-pr-523

#526 Enable SAAT with SIDAM
  infrastructure/saat.tfvars
Labels: ns:ccd-case-management-web-pr-526

#524 RDM-2239: Asylum GDPR
  src/app/footer-nav/contact-us.component.html
  src/app/footer-nav/cookies.component.html
  src/app/footer-nav/privacy.component.html
  src/app/footer-nav/tc.component.html
Labels: enhancement, ns:ccd-case-management-web-pr-524

#515 Rdm 3820 New Contract - Extract Case Search Form component
  README.md
  package.json
  src/app/cases/creator/filters/create-case-filters.component.spec.ts
  src/app/core/core.component.spec.ts
  src/app/core/core.component.ts
  src/app/core/core.module.ts
  src/app/core/pagination/pagination.service.spec.ts
  src/app/core/pagination/pagination.service.ts
  src/app/core/request.options.builder.spec.ts
  src/app/core/request.options.builder.ts
  src/app/core/search/field.model.ts
  src/app/core/search/search-input.model.ts
  src/app/core/search/search-input.test.fixture.ts
  src/app/core/search/search.service.spec.ts
  src/app/core/search/search.service.ts
  src/app/core/utils/window.service.ts
  src/app/search/search.component.html
  src/app/search/search.component.spec.ts
  src/app/search/search.component.ts
  src/app/search/search.module.ts
  src/app/shared/jurisdiction.service.ts
  src/app/shared/search/filters/search-filter.model.ts
  src/app/shared/search/filters/search-filters.component.spec.ts
  src/app/shared/search/filters/search-filters.component.ts
  src/app/shared/search/filters/search-filters.html
  src/app/shared/search/search-result-view-column.model.ts
  src/app/shared/search/search-result-view-item.model.ts
  src/app/shared/search/search-result-view.model.ts
  src/app/shared/search/search-result.component.spec.ts
  src/app/shared/search/search-result.component.ts
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.spec.ts
  src/app/shared/search/sorting/search-result-view-item-comparator-factory.ts
  src/app/shared/search/sorting/search-result-view-item-comparator.ts
  src/app/shared/search/sorting/sort-search-result.pipe.ts
  src/app/shared/shared.module.ts
  src/app/workbasket/filters/workbasket-filters.component.spec.ts
  src/app/workbasket/filters/workbasket-filters.component.ts
  src/app/workbasket/workbasket-input.model.ts
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.component.ts
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-515

#534 update-version-of-toolkit-to-2.24.1
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-534

#443 Added validation tests
  Jenkinsfile_CNP
  package.json
  test/functional-tests/features/caseCreation.feature
  test/functional-tests/features/checkYourAnswers.feature
  test/functional-tests/features/conditionalLogic.feature
  test/functional-tests/features/fieldTypes.feature
  test/functional-tests/pageObjects/basePage.js
  test/functional-tests/pageObjects/caseDetailsPage.js
  test/functional-tests/pageObjects/caseListPage.js
  test/functional-tests/pageObjects/ccd-components/caseListComponent.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdCollectionField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdComplexTypeField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdDateField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdFixedList.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdStringField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdTextAreaField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdYesNoField.js
  test/functional-tests/pageObjects/createCaseStartPage.js
  test/functional-tests/pageObjects/createCaseWizardPage.js
  test/functional-tests/pageObjects/webdriver-components/button.js
  test/functional-tests/pageObjects/webdriver-components/dropdown.js
  test/functional-tests/pageObjects/webdriver-components/textField.js
  test/functional-tests/resources/definitionsFiles/fe-automation-definition-v01.xlsx
  test/functional-tests/stepDefinitions/baseSteps.js
  test/functional-tests/stepDefinitions/caseDetailsSteps.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
  test/functional-tests/stepDefinitions/cyaSteps.js
  test/functional-tests/stepDefinitions/definitionFileSteps.js
  test/functional-tests/stepDefinitions/loginSteps.js
  test/functional-tests/stepDefinitions/testSetup.js
  test/functional-tests/stepDefinitions/validationSteps.js
  test/functional-tests/utils/fieldUtils.js
  test/functional-tests/utils/world.js
Labels: ns:ccd-case-management-web-pr-443

#508 RDM-3821 Extract Case Search Form to ui-toolkit as is
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-508

#536 Remove hmcts user as it will be the default user
  Dockerfile
Labels: ns:ccd-case-management-web-pr-536

#545 Create Docker hub Dockerfile
  Dockerfile
  hub.Dockerfile
Labels: ns:ccd-case-management-web-pr-545

#535 Feature: RDM-3915 running component from ui-toolkit
  package.json
  src/app/cases/cases.module.ts
  src/app/cases/creator/filters/create-case-filters.component.spec.ts
  src/app/cases/creator/filters/create-case-filters.component.ts
  src/app/cases/creator/filters/create-case-filters.html
  src/app/cases/creator/filters/create-case-filters.scss
  yarn.lock
Labels: ns:ccd-case-management-web-pr-535

#551 update-case-ui-toolkit-to-2-27-0
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-551

#553 update vault keys for jenkins pipeline
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
  README.md
  bin/runFunctionalTests.sh
  bin/runSmokeTests.sh
  docker-compose.tests.yml
  test/functional-tests/pageObjects/loginPage.js
  test/functional-tests/stepDefinitions/loginSteps.js
Labels: ns:ccd-case-management-web-pr-553

#555 Run Activity Service polling outside of angular
  bin/runSmokeTests.sh
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-555

#544 Rdm 3988 Initial set of search filter func tests
  .gitignore
  README.md
  package.json
  test/functional-tests/features/fieldTypes.feature
  test/functional-tests/features/search.feature
  test/functional-tests/pageObjects/basePage.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdCollectionField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdComplexTypeField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdDateField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdFixedList.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdMultiSelectField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdStringField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdTextAreaField.js
  test/functional-tests/pageObjects/ccd-components/fields/ccdYesNoField.js
  test/functional-tests/pageObjects/ccd-components/globalNavBar.js
  test/functional-tests/pageObjects/createCaseStartPage.js
  test/functional-tests/pageObjects/createCaseWizardPage.js
  test/functional-tests/pageObjects/searchPage.js
  test/functional-tests/pageObjects/webdriver-components/button.js
  test/functional-tests/pageObjects/webdriver-components/dropdown.js
  test/functional-tests/pageObjects/webdriver-components/radioField.js
  test/functional-tests/pageObjects/webdriver-components/textField.js
  test/functional-tests/resources/definitionsFiles/fe-automation-definition-v01.xlsx
  test/functional-tests/resources/definitionsFiles/fe-automation-definition-v02.xlsx
  test/functional-tests/stepDefinitions/baseSteps.js
  test/functional-tests/stepDefinitions/create-caseSteps.js
  test/functional-tests/stepDefinitions/definitionFileSteps.js
  test/functional-tests/stepDefinitions/searchSteps.js
  test/functional-tests/stepDefinitions/validationSteps.js
  test/functional-tests/utils/fieldUtils.js
  yarn.lock
Labels: enhancement, ns:ccd-case-management-web-pr-544
