Repository hmcts/ccd-case-management-web, pull requests merged in 2019-07, with the labels that each got.

#733 Remove unused id on write fixed list field
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-733

#735 DAC Fixes - Bumped up ui-toolkit version
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-735

#736 RDM-5168 - submitted Callback fix
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-736

#710 Rdm 4997 FE functional tests
  test/features/fixedListOrder.feature
  test/pageObjects/ccd-components/fields/ccdFixedList.js
  test/pageObjects/ccd-components/fields/ccdFixedRadioList.js
  test/pageObjects/ccd-components/fields/ccdMultiSelectField.js
  test/pageObjects/createCaseWizardPage.js
  test/pageObjects/webdriver-components/dropdown.js
  test/resources/definitionsFiles/fe-automation-definition-v15_RDM-4997_fixed_list_order.xlsx
  test/stepDefinitions/caseDetailsSteps.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
  test/stepDefinitions/validationSteps.js
  test/utils/fieldUtils.js
Labels: enhancement, ns:ccd-case-management-web-pr-710

#716 postcode lookup functional scenarios
  charts/ccd-case-management-web/values.aat.template.yaml
  charts/ccd-case-management-web/values.preview.template.yaml
  charts/ccd-case-management-web/values.yaml
  test/features/postcodelookup.feature
  test/pageObjects/ccd-components/fields/ccdAddressUKField.js
  test/pageObjects/createCaseWizardPage.js
  test/pageObjects/webdriver-components/dropdown.js
  test/resources/definitionsFiles/fe-automation-definition-v12_RDM-4877_showandhide_basetypes.xlsx
  test/stepDefinitions/create-caseSteps.js
  yarn.lock
Labels: ns:ccd-case-management-web-pr-716

#742 V18 Defn. File Update
  test/resources/definitionsFiles/fe-automation-definition-v15_RDM-4997_fixed_list_order.xlsx
  test/resources/definitionsFiles/fe-automation-definition-v18_RDM-4891_Postcode_Lookup.xlsx
Labels: ns:ccd-case-management-web-pr-742

#744 RDM-4279 - Bumped up toolkit release to 2.58.5
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-744

#745 RDM-5044 - Bumped up toolkit version to 2.58.6
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-745

#701 Rdm 4826
  test/README.md
  test/features/markdownOnCollectionItems.feature
  test/pageObjects/caseDetailsPage.js
  test/pageObjects/ccd-components/fields/ccdFixedList.js
  test/pageObjects/ccd-components/fields/ccdFixedRadioList.js
  test/pageObjects/ccd-components/fields/ccdMultiSelectField.js
  test/pageObjects/ccd-components/fields/ccdStringField.js
  test/resources/definitionsFiles/fe-automation-definition-v19_RDM-4826_markdown_on_collection_items.xlsx
  test/stepDefinitions/baseSteps.js
  test/stepDefinitions/caseDetailsSteps.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
  test/utils/fieldUtils.js
Labels: ns:ccd-case-management-web-pr-701

#749 updating references according to docker registry change
  Dockerfile
  acb.tpl.yaml
  charts/ccd-case-management-web/values.yaml
  docker-compose.yml
Labels: ns:ccd-case-management-web-pr-749

#743 RDM-4832 Check Your Answers functional tests
  test/features/showandhide/basicFields_CYA.feature
  test/features/showandhide/collections_CYA.feature
  test/features/showandhide/complexTypes_CYA.feature
  test/pageObjects/ccd-components/fields/ccdFixedRadioList.js
  test/pageObjects/cyaPage.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/cyaSteps.js
  test/utils/fieldUtils.js
Labels: ns:ccd-case-management-web-pr-743

#727 RDM 5022 - implement new cucumber step to improve test readability
  test/features/caseList.feature
  test/features/caseProgression.feature
  test/features/caseView.feature
  test/features/caseView_printButton.feature
  test/features/checkYourAnswers.feature
  test/features/complexTypes.feature
  test/features/complexTypesOverride.feature
  test/features/fieldTypes.feature
  test/features/nestedcollections.feature
  test/features/search.feature
  test/features/showandhide/basicFields.feature
  test/features/showandhide/collectionOfComplex.feature
  test/features/showandhide/collections.feature
  test/features/showandhide/complexTypes.feature
  test/features/showandhide/fieldInputTypes.feature
  test/stepDefinitions/baseSteps.js
  test/stepDefinitions/cyaSteps.js
  test/stepDefinitions/validationSteps.js
Labels: ns:ccd-case-management-web-pr-727

#748 RDM-4121 and RDM-3480 toolkit release
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-748

#741 Refactor FE Functional Tests for 'page contains following fields' Step
  test/features/caseView.feature
  test/features/complexTypesOverride.feature
  test/features/conditionalLogic.feature
  test/features/fixedListOrder.feature
  test/features/internalFunctionalityTesting.feature
  test/features/postcodelookup.feature
  test/pageObjects/ccd-components/complexTypes/addressComplex.js
  test/pageObjects/ccd-components/complexTypes/addressHiddenComplex.js
  test/pageObjects/ccd-components/fields/ccdAddressUK.js
  test/pageObjects/ccd-components/fields/ccdAddressUKField.js
  test/pageObjects/ccd-components/fields/ccdCollection.js
  test/pageObjects/ccd-components/fields/ccdCollectionField.js
  test/pageObjects/ccd-components/fields/ccdComplexTypeBaseField.js
  test/pageObjects/ccd-components/fields/ccdDateField.js
  test/pageObjects/ccd-components/fields/ccdDocumentField.js
  test/pageObjects/ccd-components/fields/ccdFixedList.js
  test/pageObjects/ccd-components/fields/ccdFixedRadioList.js
  test/pageObjects/ccd-components/fields/ccdMultiSelectField.js
  test/pageObjects/ccd-components/fields/ccdStringField.js
  test/pageObjects/ccd-components/fields/ccdTextAreaField.js
  test/pageObjects/ccd-components/fields/ccdYesNoField.js
  test/pageObjects/createCaseWizardPage.js
  test/pageObjects/webdriver-components/dropdown.js
  test/pageObjects/wizardPages/ComplexCollectionComplex/createCollectionOfComplexPage.js
  test/pageObjects/wizardPages/ComplexCollectionComplex/createSchoolPage.js
  test/pageObjects/wizardPages/Conditionals/conditionals_CreateACaseAND_ConditionalPage1.js
  test/pageObjects/wizardPages/Conditionals/conditionals_CreateCase_ConditionalPage1.js
  test/pageObjects/wizardPages/Conditionals/conditionals_CreateCase_ConditionalPage2.js
  test/pageObjects/wizardPages/Conditionals/conditionals_CreateCase_ConditionalPage3.js
  test/pageObjects/wizardPages/Conditionals/conditionals_CreateCase_ConditionalPage4.js
  test/pageObjects/wizardPages/dataFieldTypesPage.js
  test/stepDefinitions/baseSteps.js
  test/stepDefinitions/caseListSteps.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/cyaSteps.js
  test/stepDefinitions/definitionFileSteps.js
  test/stepDefinitions/loginSteps.js
  test/stepDefinitions/orNotEqualsSteps.js
  test/stepDefinitions/validationSteps.js
  test/utils/fieldUtils.js
Labels: ns:ccd-case-management-web-pr-741

#732 RDM-5031 - displaying thrown alert as it is instead of clearing based on search result error.
  package.json
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.component.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-732

#750 RDM-5302 Updated class-transformer, core-js and polyfills.ts
  package.json
  src/polyfills.ts
  yarn.lock
Labels: ns:ccd-case-management-web-pr-750

#697 Rdm-4754 - Functional test for show and hide bug of nested collections
  test/features/nestedcollections.feature
  test/pageObjects/ccd-components/complexTypes/addressShowAndHide.js
  test/pageObjects/wizardPages/ComplexCollectionComplex/createCollectionOfComplexPage.js
  test/resources/definitionsFiles/fe-automation-definition-v20_RDM-4745_showandhide_on_complex_collection_items.xlsx
  test/stepDefinitions/caseDetailsSteps.js
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/definitionFileSteps.js
Labels: ns:ccd-case-management-web-pr-697

#760 RDM-4835 Continue Button to respect shown fields on page
  test/features/continueButton.feature
  test/pageObjects/wizardPages/Conditionals/conditionals_CreateCase_ConditionalPage1.js
  test/resources/definitionsFiles/fe-automation-definition-v21_RDM-4835_continueButton.xlsx
  test/stepDefinitions/create-caseSteps.js
  test/stepDefinitions/validationSteps.js
Labels: ns:ccd-case-management-web-pr-760

#758 RDM-4692 ccd-write-address-field id fix
  package.json
  yarn.lock
Labels: ns:ccd-case-management-web-pr-758
