Repository hmcts/ccd-case-management-web, pull requests merged in 2020-04, with the labels that each got.

#893 RDM-7843-Stale-PR
  .github/stale.yml
Labels: ns:ccd, rel:ccd-case-management-web-pr-893

#926 RDM-8126
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/requirements.yaml
Labels: ns:ccd, rel:ccd-case-management-web-pr-926

#928 RDM-7491: Fix Management Web error on /config endpoint
  Dockerfile
  package.json
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/app/app.module.ts
  src/app/core/interceptor/requestinterceptor.ts
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-928

#932 Remove Custom Preview URLs and restore defaults
  charts/ccd-case-management-web/values.preview.template.yaml
Labels: ns:ccd, rel:ccd-case-management-web-pr-932

#937 RDM-8348 Media Viewer Upgrade
  package.json
  src/app/mv-wrapper/media-viewer-wrapper.component.html
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-937
