Repository hmcts/ccd-case-management-web, pull requests merged in 2020-02, with the labels that each got.

#876 fix broken build
  .nvmrc
Labels: ns:ccd, rel:ccd-case-management-web-pr-876

#864 Rdm 6998 Add new multimedia file types to media viewer func tests. Enable media viewer func tests.
  charts/ccd-case-management-web/values.preview.template.yaml
  test/features/media-viewer.feature
  test/pageObjects/caseDetailsPage.js
  test/resources/documents_for_mv/document_avi_1.avi
  test/resources/documents_for_mv/document_avi_2.Avi
  test/resources/documents_for_mv/document_mov_1.mov
  test/resources/documents_for_mv/document_mov_2.MoV
  test/resources/documents_for_mv/document_mp3_1.mp3
  test/resources/documents_for_mv/document_mp3_2.Mp3
  test/stepDefinitions/caseDetailsSteps.js
Labels: enhancement, ns:ccd, rel:ccd-case-management-web-pr-864

#874 Release cut 17.1
  .nvmrc
  charts/ccd-case-management-web/values.preview.template.yaml
  package.json
  src/app/app.config.ts
  src/app/cases/creator/case-creator.component.spec.ts
  src/app/core/banner/banner.component.scss
  src/app/core/banner/banner.component.spec.ts
  src/app/core/banner/banner.component.ts
  src/app/core/banner/banner.html
  src/app/core/banner/banner.module.ts
  src/app/core/core.component.html
  src/app/core/core.component.spec.ts
  src/app/core/core.component.ts
  src/app/core/core.module.ts
  src/app/search/search.component.spec.ts
  src/app/workbasket/workbasket.component.spec.ts
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-874

#857 RDM-6965 - Jurisdiction-Level Shuttering
  README.md
  charts/ccd-case-management-web/values.preview.template.yaml
  charts/ccd-case-management-web/values.yaml
  infrastructure/main.tf
  infrastructure/preview.tfvars
  package.json
  server.ts
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/app/app.routing.ts
  src/app/cases/creator/case-creator.component.spec.ts
  src/app/core/core.component.spec.ts
  src/app/core/core.component.ts
  src/app/core/core.module.ts
  src/app/core/pagination/pagination.service.spec.ts
  src/app/core/profile/profile.resolver.spec.ts
  src/app/core/profile/profile.resolver.ts
  src/app/shutter/shutter-routing.module.ts
  src/app/shutter/shutter.component.html
  src/app/shutter/shutter.component.ts
  src/app/shutter/shutter.module.ts
  src/public/config.json
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-857

#879 RDM-7554 Remove the deprecated enableDockerBuild
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-management-web-pr-879

#881 Rdm 7524: Wording Updates to CCD Shuttering and Redirection to Expert UI
  charts/ccd-case-management-web/values.preview.template.yaml
  package.json
  src/app/shutter/shutter.component.html
  src/app/shutter/shutter.component.ts
  test/pageObjects/ccd-components/globalNavBar.js
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-881

#882 RDM-7459 - Update CTSC details
  src/app/footer-nav/contact-us.component.html
Labels: ns:ccd, rel:ccd-case-management-web-pr-882

#883 RDM-3593 - Update to node 12.x - MASTER
  .nvmrc
  .travis.yml
  Dockerfile
  README.md
  hub.Dockerfile
  infrastructure/main.tf
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-883

#885 RDM-7695 Update-IDAM-URLs
  infrastructure/ithc.tfvars
Labels: ns:ccd, rel:ccd-case-management-web-pr-885

#884 RDM-7479
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-884
