Repository hmcts/ccd-case-management-web, pull requests merged in 2020-09, with the labels that each got.

#951 Pay 4.0.0-beta87
  package.json
  test/features/caseFilters.feature
  test/features/caseList.feature
  test/features/caseUpdate.feature
  test/features/caseView.feature
  test/features/complexTypesOverride.feature
  test/features/continueButton.feature
  test/features/fieldTypes.feature
  test/features/media-viewer.feature
  test/features/nestedcollections.feature
  test/features/search.feature
  test/features/showandhide/basicFields.feature
  test/features/showandhide/collectionOfComplex.feature
  test/features/showandhide/collections.feature
  test/features/showandhide/collections_CYA.feature
  test/features/showandhide/complexTypes.feature
  test/features/showandhide/complexTypes_CYA.feature
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-951

#974 Yarn lock fix on develop
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-974

#967 RDM-9299 - bump dot-prop to 4.2.1 i.e fix for
  Jenkinsfile_CNP
  bin/run-yarn-audit.sh
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-967

#978 Rdm 9438 to develop
  karma.conf.js
  package.json
  src/app/core/core.component.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-978

#972 RDM-9377 Case Management Web: Resolve Dependapot Vulnerability Alerts on Github
  karma.conf.js
  package.json
  src/app/core/core.component.spec.ts
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-972

#981 IE11 fix - lowering class-transformer to ^0.2.3
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-981
