Repository hmcts/ccd-case-management-web, pull requests merged in 2020-03, with the labels that each got.

#890 Migrate to aks
  Dockerfile
  Jenkinsfile_CNP
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/requirements.yaml
  charts/ccd-case-management-web/values.aat.template.yaml
  charts/ccd-case-management-web/values.preview.template.yaml
  charts/ccd-case-management-web/values.yaml
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-890

#898 Archive test results for jenkins
  .gitignore
  bin/runFunctionalTests.sh
  bin/runSmokeTests.sh
  test/config/conf.js
Labels: ns:ccd, rel:ccd-case-management-web-pr-898

#897 RDM-7867-Update-base-chart
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/requirements.yaml
Labels: ns:ccd, rel:ccd-case-management-web-pr-897

#903 Stop deploying to ASE on AAT
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-management-web-pr-903

#900 fix flaky func tests on login page:
  test/pageObjects/loginPage.js
Labels: ns:ccd, rel:ccd-case-management-web-pr-900

#892 RDM-7841 Bump up unit test coverage
  Dockerfile
  karma.conf.js
  src/app/app.config.spec.ts
  src/app/core/ccd-browser-support/ccd-browser-support.component.spec.ts
  yarn.lock
Labels: ns:ccd, rel:ccd-case-management-web-pr-892

#904 Revert "fix flaky func tests on login page: (#900)"
  test/pageObjects/loginPage.js
Labels: ns:ccd, rel:ccd-case-management-web-pr-904

#909 fix for test
  test/pageObjects/webdriver-components/dropdown.js
Labels: ns:ccd, rel:ccd-case-management-web-pr-909

#913 RDM-7932 - demo print url update
  infrastructure/demo.tfvars
Labels: ns:ccd, rel:ccd-case-management-web-pr-913

#916 Update dm url remote
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/values.yaml
Labels: ns:ccd, rel:ccd-case-management-web-pr-916

#920 reenable functional and smoke tests
  charts/ccd-case-management-web/values.preview.template.yaml
  package.json
Labels: ns:ccd, rel:ccd-case-management-web-pr-920

#921 re-enable the temporarily disabled test
  test/features/caseUpdate.feature
Labels: ns:ccd, rel:ccd-case-management-web-pr-921

#923 AKS prod migration
  Jenkinsfile_CNP
Labels: ns:ccd, rel:ccd-case-management-web-pr-923

#914 Rdm-7924: Handle no user profile in the front end
  src/app/core/core.component.spec.ts
  src/app/core/core.component.ts
  src/app/workbasket/workbasket.component.spec.ts
  src/app/workbasket/workbasket.component.ts
Labels: ns:ccd, rel:ccd-case-management-web-pr-914

#924 Terraform cleanup
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/outputs.tf
  infrastructure/perftest.tfvars
  infrastructure/preview.tfvars
  infrastructure/prod.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
Labels: ns:ccd, rel:ccd-case-management-web-pr-924
