Repository hmcts/ccd-case-management-web, pull requests merged in 2021-02, with the labels that each got.

#1011 RDM-10962: Document uploads not enabling continue button on CCD
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1011

#1006 RDM-4473: Add AppInsights to ccd-case-management-web
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/values.preview.template.yaml
  charts/ccd-case-management-web/values.yaml
  config/custom-environment-variables.yaml
  config/default.yaml
  infrastructure/.terraform-version
  infrastructure/outputs.tf
  package.json
  server.ts
  sonar-project.properties
  src/app/app-insights/app-insights.ts
  src/app/app.config.spec.ts
  src/app/app.config.ts
  src/public/config.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1006

#1020 serve font files as static resources
  src/public/assets/fonts/bold-fb2676462a-v1.eot
  src/public/assets/fonts/light-2c037cf7e1-v1.eot
  src/public/assets/fonts/light-458f8ea81c-v1.woff
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1020

#1023 Role name corrected
  config/default.yaml
  server.ts
  src/public/config.json
Labels: DO *NOT* MERGE, ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1023

#1022 Disabled AI
  config/default.yaml
  server.ts
  src/public/config.json
Labels: DO *NOT* MERGE, ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1022

#1026 RDM-11245: Add logging for page validation
  package.json
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1026

#946 Develop
  yarn-audit-known-issues
Labels: DO_NOT_MERGE, ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-946
