Repository hmcts/ccd-case-management-web, pull requests merged in 2021-04, with the labels that each got.

#1036 Release Cut 21.2
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1036

#1046 Fix all latest cves
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1046

#1032 RDM-11179: Re-enable app insights without any delay in page loading
  charts/ccd-case-management-web/Chart.yaml
  charts/ccd-case-management-web/values.yaml
  server.ts
  src/app/app-insights/app-insights.ts
  src/app/app.config.spec.ts
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1032

#1041 RDM-11843 & RDM-11919 & RDM-12057 - bump up dependencies to resolve CVEs
  charts/ccd-case-management-web/values.preview.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1041

#1051 Create scheduled-dummy-commit.yml
  .github/workflows/scheduled-dummy-commit.yml
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1051

#1050 RDM-12109: Remove directory name from COPY command
  Dockerfile
Labels: ns:ccd, prd:ccd, rel:ccd-case-management-web-pr-1050
